#!/usr/bin/env python3
"""QSVT-style polynomial eigenvalue transform, certified against the spectrum.

Applies a polynomial P to an operator's eigenvalues (rescaled to [-1,1]) and checks
that the transformed spectrum lies inside P evaluated, in interval arithmetic, over
the certified eigenvalue enclosures.

CLAIM BOUNDARY: certified polynomial transform of a finite Hermitian spectrum;
classical-reference of what QSVT realises on hardware. Not a continuum/Millennium claim.
"""
from __future__ import annotations

import argparse
import json
import sys
import warnings
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

warnings.filterwarnings("ignore")

from gaugegap.curverank_registry import get_operator
from gaugegap.quantum.qsvt import qsvt_eigenvalue_transform


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--operator", default="berry_keating_xp")
    ap.add_argument("--n-basis", type=int, default=8)
    ap.add_argument("--coeffs", default="0,0,1",
                    help="monomial coefficients low->high (default x^2)")
    ap.add_argument("--output-dir", type=Path, default=ROOT / "results" / "qsvt")
    args = ap.parse_args()

    spec = get_operator(args.operator)
    H = spec.build(args.n_basis)
    coeffs = [float(c) for c in args.coeffs.split(",") if c.strip() != ""]
    r = qsvt_eigenvalue_transform(H, coeffs)

    print("=" * 72)
    print(f"QSVT eigenvalue transform — {spec.name} (n_basis={args.n_basis})")
    print("=" * 72)
    print(f"  polynomial coeffs (low->high): {coeffs}")
    print(f"  spectral window rescaled to [-1,1]: {tuple(round(x,4) for x in r.window)}")
    print(f"  transformed eigenvalues inside certified P-enclosures: {r.all_inside}")
    print(f"  max residual vs reference: {r.max_residual:.2e}")

    out = args.output_dir
    out.mkdir(parents=True, exist_ok=True)
    (out / "qsvt.json").write_text(json.dumps(r.to_dict(), indent=2, sort_keys=True))
    lines = [
        "# QSVT eigenvalue transform (certified)",
        "",
        f"Operator `{spec.name}` (n_basis {args.n_basis}); polynomial coeffs "
        f"`{coeffs}` (monomial, low→high). **Claim boundary:** a certified polynomial "
        "transform of a finite Hermitian spectrum (the classical reference of what "
        "QSVT realises on hardware); not a continuum/Millennium claim.",
        "",
        f"- Transformed eigenvalues inside the interval-evaluated certified "
        f"enclosures: **{r.all_inside}**",
        f"- Max residual vs reference: **{r.max_residual:.2e}**",
        "",
        "Each transformed eigenvalue P(λ) is bracketed by P([lo,hi]) evaluated in "
        "interval arithmetic over the certified eigenvalue enclosures.",
        "",
        "_Generated by `scripts/run_qsvt.py`._",
    ]
    (out / "qsvt.md").write_text("\n".join(lines) + "\n")
    print(f"\nReport: {out / 'qsvt.json'} (+ .md)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
