#!/usr/bin/env python3
"""Scaling study for the certified eigenvalue kernel.

Measures wall-clock time and the widest certified enclosure as the truncation size
grows, for the Berry-Keating xp operator (or any registered operator). Documents
the practical cost of the rigorous interval kernel honestly: it is exact-arithmetic
and roughly O(n^3), so it targets small-to-moderate dense matrices.

CLAIM BOUNDARY: a benchmark of the verification kernel's cost/accuracy at finite
truncations. Not a physics or continuum claim.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from gaugegap.curverank_registry import get_operator
from gaugegap.certify import certify_spectrum


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--operator", default="berry_keating_xp")
    ap.add_argument("--sizes", default="4,8,16,32",
                    help="comma-separated truncation sizes")
    ap.add_argument("--output-dir", type=Path, default=ROOT / "results" / "certify-scaling")
    args = ap.parse_args()

    spec = get_operator(args.operator)
    sizes = [int(s) for s in args.sizes.split(",") if s.strip()]

    rows = []
    print("=" * 64)
    print(f"Certify scaling — {spec.name}")
    print("=" * 64)
    for n in sizes:
        H = spec.build(n)
        t0 = time.perf_counter()
        cert = certify_spectrum(H)
        dt = time.perf_counter() - t0
        ev = np.linalg.eigvalsh((H + H.conj().T) / 2)
        all_bracket = all(lo - 1e-9 <= ev[i] <= hi + 1e-9
                          for i, (lo, hi) in enumerate(cert.enclosures))
        rows.append({
            "n_basis": n, "dim": int(H.shape[0]), "seconds": dt,
            "max_enclosure_width": cert.max_width,
            "all_classical_bracketed": bool(all_bracket),
        })
        print(f"  n={n:>3} dim={H.shape[0]:>3} | {dt:7.3f}s | max width "
              f"{cert.max_width:.2e} | brackets {all_bracket}")

    payload = {
        "operator": spec.name,
        "claim_boundary": ("benchmark of the rigorous interval kernel cost/accuracy "
                           "at finite truncations; not a physics or continuum claim"),
        "rows": rows,
    }
    out = args.output_dir
    out.mkdir(parents=True, exist_ok=True)
    (out / "certify-scaling.json").write_text(json.dumps(payload, indent=2, sort_keys=True))
    lines = ["# Certify scaling study", "",
             f"Operator `{spec.name}`. Rigorous interval kernel is exact-arithmetic "
             "(~O(n^3)); these are finite-truncation benchmarks, not a physics claim.",
             "", "| n_basis | dim | seconds | max enclosure width | classical bracketed |",
             "|---|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['n_basis']} | {r['dim']} | {r['seconds']:.3f} | "
                     f"{r['max_enclosure_width']:.2e} | {r['all_classical_bracketed']} |")
    lines += ["", "_Generated by `scripts/run_certify_scaling.py`._"]
    (out / "certify-scaling.md").write_text("\n".join(lines) + "\n")
    print(f"\nReport: {out / 'certify-scaling.json'} + {out / 'certify-scaling.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
