#!/usr/bin/env python3
"""Validate quantum eigenvalue estimates against the certified interval kernel.

For a chosen operator, runs each requested quantum method (ESPRIT, QCELS, Krylov,
QPE) and reports whether its estimates land inside the certified eigenvalue
enclosures, with residuals against the classical exact spectrum. ESPRIT/QCELS/
Krylov are pure-numpy; QPE uses the local Aer emulator (or an IBM device).

CLAIM BOUNDARY: finite-operator spectral screening + method benchmark. The
certified enclosures are rigorous; quantum estimates here are simulation. This is
not a proof of the Riemann Hypothesis or any Millennium Prize problem.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from gaugegap.quantum_validation import validate_operator

CLAIM_BOUNDARY = (
    "finite-operator spectral screening + method benchmark; certified negative "
    "result; not a proof of the Riemann Hypothesis or any Millennium Prize "
    "problem; quantum estimates are simulation"
)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--operator", type=str, default="berry_keating_xp")
    ap.add_argument("--n-basis", type=int, default=8)
    ap.add_argument("--methods", type=str, default="esprit,qcels,krylov",
                    help="comma-separated: esprit,qcels,krylov,qpe")
    ap.add_argument("--k-zeros", type=int, default=20)
    ap.add_argument("--shots", type=int, default=None)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--emulator", action="store_true",
                    help="QPE on local Aer (default if no --device)")
    ap.add_argument("--device", type=str, default="",
                    help="IBM backend for the QPE method (needs credentials)")
    ap.add_argument("--output-dir", type=Path,
                    default=ROOT / "results" / "quantum-validation")
    args = ap.parse_args()

    methods = tuple(m.strip() for m in args.methods.split(",") if m.strip())
    use_emulator = not args.device

    print("=" * 72)
    print(f"Quantum-validation harness — operator {args.operator}, "
          f"n_basis {args.n_basis}")
    print("=" * 72)

    reports = validate_operator(
        args.operator, args.n_basis, methods=methods, k_zeros=args.k_zeros,
        seed=args.seed, shots=args.shots, use_emulator=use_emulator,
        device=args.device,
    )

    payload = {
        "operator": args.operator,
        "n_basis": args.n_basis,
        "k_zeros": args.k_zeros,
        "claim_boundary": CLAIM_BOUNDARY,
        "methods": {m: r.to_dict() for m, r in reports.items()},
    }
    for m, r in reports.items():
        print(f"  {m:>7}: {r.n_in_enclosure}/{r.n_estimates} in certified "
              f"enclosure | max residual {r.max_abs_residual:.2e} | "
              f"all_certified {r.all_certified}")

    out = args.output_dir
    out.mkdir(parents=True, exist_ok=True)
    (out / "quantum-validation.json").write_text(json.dumps(payload, indent=2,
                                                            sort_keys=True))
    _write_markdown(out / "quantum-validation.md", payload)
    print(f"\nReport: {out / 'quantum-validation.json'} + "
          f"{out / 'quantum-validation.md'}")
    return 0


def _write_markdown(path: Path, payload: dict) -> None:
    lines = [
        "# Quantum-validation report",
        "",
        f"Operator `{payload['operator']}`, n_basis **{payload['n_basis']}**. "
        "Each quantum method's eigenvalue estimates are checked against the "
        "certified interval enclosures. **Claim boundary:** finite-system "
        "spectral screening + method benchmark; a certified negative-result "
        "screening; not a proof of the Riemann Hypothesis or any Millennium "
        "Prize problem; quantum estimates are simulation.",
        "",
        "| Method | In certified enclosure | Max residual vs classical | All certified |",
        "|---|---|---|---|",
    ]
    for m, r in payload["methods"].items():
        lines.append(
            f"| {m} | {r['n_in_enclosure']} | {r['max_abs_residual']:.2e} | "
            f"{r['all_certified']} |"
        )
    lines += ["", "_Generated by `scripts/run_quantum_validation.py`._"]
    path.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
