#!/usr/bin/env python3
"""Entanglement-formation dynamics: measure how entanglement BUILDS UP over time
in a finite two-qubit exchange model, with an S(t) figure.

Inspired by attosecond-entanglement work (entanglement forms over a finite time).
CLAIM BOUNDARY: finite-model demonstration; NOT a reproduction of the helium
experiment or the ~232 as figure; physical-time conversion is illustrative only.
"""
from __future__ import annotations
import argparse, json, sys, warnings
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parents[1]; SRC = ROOT / "src"
if str(SRC) not in sys.path: sys.path.insert(0, str(SRC))
warnings.filterwarnings("ignore")
from gaugegap.quantum.entanglement_dynamics import simulate_buildup, two_qubit_exchange_model
from gaugegap.visualization.svg import SVGCanvas


def _plot(path, times, ent, tb, s_max, unit):
    W = H = 520; pad = 60
    tmax = max(times) or 1.0; smax = max(s_max, max(ent), 1e-9)
    c = SVGCanvas(W, H)
    c.line(pad, H - pad, W - pad, H - pad, stroke="#30363d")   # x
    c.line(pad, pad, pad, H - pad, stroke="#30363d")           # y
    def tf(t, s):
        return (pad + t / tmax * (W - 2 * pad), (H - pad) - s / smax * (H - 2 * pad))
    c.polyline([tf(t, s) for t, s in zip(times, ent)], stroke="#58a6ff", stroke_width=2.0)
    # asymptote + build-up marker
    ya = (H - pad) - s_max / smax * (H - 2 * pad)
    c.line(pad, ya, W - pad, ya, stroke="#8b949e", stroke_width=1.0, opacity=0.5)
    xb = pad + tb / tmax * (W - 2 * pad)
    c.line(xb, pad, xb, H - pad, stroke="#f0c674", stroke_width=1.5, opacity=0.8)
    c.text(W / 2, 28, "Entanglement build-up  S(t)", size=15)
    c.text(W / 2, H - 22, f"time ({unit})  -  build-up (gold) at t={tb:.3g}", size=11,
           fill="#8b949e")
    c.text(pad + 6, pad + 4, "S = ln 2", size=10, fill="#8b949e", anchor="start")
    c.write(path)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--coupling", type=float, default=1.0)
    ap.add_argument("--detuning", type=float, default=0.0)
    ap.add_argument("--t-max", type=float, default=1.6)
    ap.add_argument("--samples", type=int, default=300)
    ap.add_argument("--fraction", type=float, default=0.9)
    ap.add_argument("--energy-scale-ev", type=float, default=None,
                    help="illustrative only: convert model time to attoseconds")
    ap.add_argument("--output-dir", type=Path, default=ROOT / "results" / "entanglement-dynamics")
    args = ap.parse_args()
    H, psi0 = two_qubit_exchange_model(args.coupling, args.detuning)
    r = simulate_buildup(H, psi0, t_max=args.t_max, n_samples=args.samples,
                         fraction=args.fraction, energy_scale_eV=args.energy_scale_ev)
    print("=" * 72)
    print("Entanglement-formation dynamics (two-qubit exchange model)")
    print("=" * 72)
    print(f"  S(0)={r.entropies[0]:.4f}  ->  S_max={r.s_asymptote:.4f} (ln2={np.log(2):.4f})")
    print(f"  build-up time ({int(args.fraction*100)}% of max): "
          f"{r.buildup_time:.4g} {r.time_unit}")
    if r.time_unit == "attoseconds":
        print(f"  (illustrative conversion at E={args.energy_scale_ev} eV; not the "
              f"TU Wien measurement)")
    out = args.output_dir; out.mkdir(parents=True, exist_ok=True)
    (out / "entanglement-dynamics.json").write_text(json.dumps(r.to_dict(), indent=2, sort_keys=True))
    _plot(out / "entanglement_buildup.svg", r.times, r.entropies, r.buildup_time,
          r.s_asymptote, r.time_unit)
    (out / "entanglement-dynamics.md").write_text(
        "# Entanglement-formation dynamics\n\n"
        "Finite two-qubit exchange model: an excitation localized on one qubit builds "
        "entanglement with its partner over a finite time. **Claim boundary:** a "
        "finite-model demonstration inspired by attosecond-entanglement work; NOT a "
        "reproduction of the helium experiment or the ~232 as figure; physical-time "
        "conversion is illustrative only.\n\n"
        f"- S(0) = {r.entropies[0]:.4f}, S_max = {r.s_asymptote:.4f} (ln 2 = "
        f"{np.log(2):.4f})\n"
        f"- build-up time ({int(args.fraction*100)}% of max) = "
        f"**{r.buildup_time:.4g} {r.time_unit}**\n\n"
        "![S(t)](entanglement_buildup.svg)\n\n"
        "_Generated by `scripts/run_entanglement_dynamics.py`._\n")
    print(f"\nReport: {out / 'entanglement-dynamics.json'} (+ .md, .svg)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
