#!/usr/bin/env python3
"""Certified energy/gap bracket: rigorous interval LOWER bound + quantum variational
UPPER bound, with a discharged Lean/Coq certificate.

For a chosen operator, computes [certified_lower, ritz_upper] for E0 (and the gap),
cross-checks that the exact eigenvalue lies inside, and emits machine-checkable
Lean4/Coq bracket certificates.

CLAIM BOUNDARY: rigorous finite-matrix eigenvalue/gap bracket; certified lower +
variational (Ritz) upper; simulation-level; not a continuum/Millennium claim.
"""
from __future__ import annotations

import argparse
import json
import sys
import warnings
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

warnings.filterwarnings("ignore")

from gaugegap.curverank_registry import get_operator
from gaugegap.certified_bracket import (
    certified_ground_bracket, certified_gap_bracket, bracket_contains_exact,
)
from gaugegap.rigorous.bracket_certificate import emit_bracket_certificate


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--operator", default="berry_keating_xp")
    ap.add_argument("--n-basis", type=int, default=8)
    ap.add_argument("--n-iterations", type=int, default=16)
    ap.add_argument("--output-dir", type=Path, default=ROOT / "results" / "certified-bracket")
    args = ap.parse_args()

    spec = get_operator(args.operator)
    H = spec.build(args.n_basis)
    Hh = (H + H.conj().T) / 2.0
    ev = np.linalg.eigvalsh(Hh)

    ground = certified_ground_bracket(H, n_iterations=args.n_iterations)
    gap = certified_gap_bracket(H, n_iterations=args.n_iterations)
    inside = bracket_contains_exact(H, ground)
    cert = emit_bracket_certificate("E0", ground.lower, ground.upper)

    print("=" * 72)
    print(f"Certified bracket — {spec.name} (n_basis={args.n_basis})")
    print("=" * 72)
    print(f"  E0 in [{ground.lower:.8f}, {ground.upper:.8f}]  width {ground.width:.2e}")
    print(f"     exact E0 = {ev[0]:.8f}   inside bracket: {inside}")
    gb = gap["gap_bracket"]
    print(f"  gap in [{gb['lower']:.8f}, {gb['upper']:.8f}]  "
          f"(true gap {ev[1]-ev[0]:.8f})")
    print(f"  lower = certified interval kernel | upper = quantum Krylov Ritz value")

    payload = {
        "operator": spec.name, "n_basis": args.n_basis,
        "ground": ground.to_dict(), "gap": gap,
        "exact_E0": float(ev[0]), "exact_gap": float(ev[1] - ev[0]),
        "exact_inside_bracket": bool(inside),
        "bracket_certificate": cert.to_dict(),
    }
    out = args.output_dir
    out.mkdir(parents=True, exist_ok=True)
    (out / "certified-bracket.json").write_text(json.dumps(payload, indent=2, sort_keys=True))
    (out / "bracket_E0.lean").write_text(cert.lean4)
    (out / "bracket_E0.coq").write_text(cert.coq)
    _write_markdown(out / "certified-bracket.md", payload)
    print(f"\nReport: {out / 'certified-bracket.json'} (+ .md, bracket_E0.lean/.coq)")
    return 0


def _write_markdown(path: Path, p: dict) -> None:
    g = p["ground"]; gb = p["gap"]["gap_bracket"]
    lines = [
        "# Certified energy/gap bracket",
        "",
        f"Operator `{p['operator']}` (n_basis {p['n_basis']}). **Claim boundary:** a "
        "rigorous finite-matrix bracket — certified interval **lower** bound + quantum "
        "variational (Ritz) **upper** bound. Simulation-level; not a continuum or "
        "Millennium claim.",
        "",
        f"- **E0** ∈ [{g['lower']:.8f}, {g['upper']:.8f}]  (width {g['width']:.2e}); "
        f"exact E0 = {p['exact_E0']:.8f}, inside: **{p['exact_inside_bracket']}**",
        f"- **gap** ∈ [{gb['lower']:.8f}, {gb['upper']:.8f}]  "
        f"(true gap {p['exact_gap']:.8f})",
        "",
        "Lower bounds come from the verified interval-arithmetic kernel; upper bounds "
        "are quantum Krylov Ritz values (upper bounds on eigenvalues by "
        "Courant-Fischer). A discharged Lean 4 / Coq certificate of `lower ≤ E0 ≤ "
        "upper` is emitted (`bracket_E0.lean` / `.coq`).",
        "",
        "_Generated by `scripts/run_certified_bracket.py`._",
    ]
    path.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
