#!/usr/bin/env python3
"""Finite Lindbladian open-system steady state (dependency-light, numpy).

Builds a small dissipative spin chain (transverse-field Ising + per-site
amplitude damping), finds the steady state from the Liouvillian null space, reports
the relaxation gap, and cross-validates against long-time evolution.

CLAIM BOUNDARY: exact finite open-system computation, cross-validated; non-Hermitian
Liouvillian (not interval-certified); not a continuum/Millennium claim.
"""
from __future__ import annotations
import argparse, json, sys, warnings
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parents[1]; SRC = ROOT / "src"
if str(SRC) not in sys.path: sys.path.insert(0, str(SRC))
warnings.filterwarnings("ignore")
from gaugegap.quantum.open_system import (
    lindbladian_superoperator, solve_open_system, evolve, steady_state_observable,
)

_X = np.array([[0, 1], [1, 0]], dtype=complex)
_Z = np.array([[1, 0], [0, -1]], dtype=complex)
_SM = np.array([[0, 1], [0, 0]], dtype=complex)
_I = np.eye(2, dtype=complex)


def _op(local, site, n):
    out = np.array([[1.0 + 0j]])
    for q in range(n):
        out = np.kron(out, local if q == site else _I)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--n-sites", type=int, default=2)
    ap.add_argument("--field", type=float, default=1.0)
    ap.add_argument("--coupling", type=float, default=1.0)
    ap.add_argument("--gamma", type=float, default=0.3)
    ap.add_argument("--output-dir", type=Path, default=ROOT / "results" / "open-system")
    args = ap.parse_args()
    n = args.n_sites
    H = np.zeros((2 ** n, 2 ** n), dtype=complex)
    for q in range(n):
        H += args.field * _op(_X, q, n)
    for q in range(n - 1):
        H += args.coupling * _op(_Z, q, n) @ _op(_Z, q + 1, n)
    jumps = [np.sqrt(args.gamma) * _op(_SM, q, n) for q in range(n)]
    res = solve_open_system(H, jumps)
    L = lindbladian_superoperator(H, jumps)
    rho_long = evolve(L, np.eye(2 ** n) / 2 ** n, 80.0)
    long_match = bool(np.allclose(rho_long, res.steady_state, atol=1e-3))
    mag = steady_state_observable(res.steady_state, sum(_op(_Z, q, n) for q in range(n)))

    print("=" * 72)
    print(f"Open system — {n}-site TFIM + amplitude damping (gamma={args.gamma})")
    print("=" * 72)
    print(f"  valid density matrix: {res.is_valid_density_matrix}  "
          f"residual ||L rho||={res.residual_norm:.2e}")
    print(f"  relaxation gap: {res.relaxation_gap:.4f}  | steady <sum Z>={mag:.4f}")
    print(f"  steady state == long-time evolution: {long_match}")
    out = args.output_dir; out.mkdir(parents=True, exist_ok=True)
    payload = res.to_dict()
    payload.update({"n_sites": n, "gamma": args.gamma,
                    "steady_total_Z": mag, "long_time_matches": long_match})
    (out / "open-system.json").write_text(json.dumps(payload, indent=2, sort_keys=True))
    (out / "open-system.md").write_text(
        f"# Lindbladian open-system steady state\n\n"
        f"{n}-site transverse-field Ising + per-site amplitude damping "
        f"(gamma={args.gamma}). **Claim boundary:** exact finite open-system "
        f"computation, cross-validated; non-Hermitian Liouvillian (not interval-"
        f"certified); not a continuum/Millennium claim.\n\n"
        f"- valid density matrix: **{res.is_valid_density_matrix}**, "
        f"residual ||L rho|| = {res.residual_norm:.2e}\n"
        f"- relaxation gap: **{res.relaxation_gap:.4f}**; steady <sum Z> = {mag:.4f}\n"
        f"- steady state matches long-time evolution: **{long_match}**\n\n"
        f"_Generated by `scripts/run_open_system.py`._\n")
    print(f"\nReport: {out / 'open-system.json'} (+ .md)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
