#!/usr/bin/env python3
"""Temple-Kato certified ground-energy bracket from a quantum trial state.

Pairs the Temple lower bound (from an imaginary-time trial state + the certified E1
lower bound) with the variational upper bound <H>, emitting a discharged Lean/Coq
bracket certificate. CLAIM BOUNDARY: rigorous finite-matrix bracket; simulation-
level trial state; not a continuum/Millennium claim.
"""
from __future__ import annotations
import argparse, json, sys, warnings
from pathlib import Path
import numpy as np
ROOT = Path(__file__).resolve().parents[1]; SRC = ROOT / "src"
if str(SRC) not in sys.path: sys.path.insert(0, str(SRC))
warnings.filterwarnings("ignore")
from gaugegap.curverank_registry import get_operator
from gaugegap.quantum.temple_kato import certified_temple_bracket


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--operator", default="berry_keating_xp")
    ap.add_argument("--n-basis", type=int, default=8)
    ap.add_argument("--beta", type=float, default=0.6)
    ap.add_argument("--output-dir", type=Path, default=ROOT / "results" / "temple-bracket")
    args = ap.parse_args()
    spec = get_operator(args.operator)
    H = spec.build(args.n_basis)
    b = certified_temple_bracket(H, beta=args.beta)
    ev = float(np.linalg.eigvalsh((H + H.conj().T) / 2)[0])
    print("=" * 72)
    print(f"Temple-Kato bracket — {spec.name} (n_basis={args.n_basis})")
    print("=" * 72)
    print(f"  E0 in [{b.lower:.8f}, {b.upper:.8f}]  (Temple lower, variational upper)")
    print(f"     exact E0 = {ev:.8f}  inside: {b.contains_exact}")
    print(f"     mu (certified E1 lower) = {b.mu:.6f}; interval-kernel lower = "
          f"{b.interval_lower:.6f}")
    out = args.output_dir; out.mkdir(parents=True, exist_ok=True)
    (out / "temple-bracket.json").write_text(json.dumps(b.to_dict(), indent=2, sort_keys=True))
    (out / "bracket_E0_temple.lean").write_text(b.lean4)
    (out / "bracket_E0_temple.coq").write_text(b.coq)
    (out / "temple-bracket.md").write_text(
        f"# Temple-Kato ground-energy bracket\n\n"
        f"Operator `{spec.name}` (n_basis {args.n_basis}). **Claim boundary:** a "
        f"rigorous finite-matrix bracket from a quantum trial state (Temple lower + "
        f"variational upper); simulation-level; not a continuum/Millennium claim.\n\n"
        f"- E0 in **[{b.lower:.8f}, {b.upper:.8f}]**; exact E0 = {ev:.8f}, "
        f"inside: **{b.contains_exact}**\n"
        f"- mu (certified E1 lower) = {b.mu:.6f}; interval-kernel lower = "
        f"{b.interval_lower:.6f}\n\n"
        f"Discharged Lean/Coq certificate of `lower <= E0 <= upper` emitted "
        f"(`bracket_E0_temple.lean`/`.coq`).\n\n"
        f"_Generated by `scripts/run_temple_bracket.py`._\n")
    print(f"\nReport: {out / 'temple-bracket.json'} (+ .md, .lean, .coq)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
