#!/usr/bin/env python3
"""Independently machine-verify every certified-inequality schema with z3.

The repo's certificates are emitted as discharged Lean 4 / Coq (grep-checked for
holes). This runner adds a second, automated witness: z3 proves each certified
inequality valid over the reals (the negated conclusion is unsatisfiable). Exits
non-zero if any schema fails to verify.

CLAIM BOUNDARY: an automated real-arithmetic cross-check of the certificates, not a
new physical claim.
"""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; SRC = ROOT / "src"
if str(SRC) not in sys.path: sys.path.insert(0, str(SRC))
from gaugegap.rigorous.smt_certificates import verify_all


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--output-dir", type=Path, default=ROOT / "results" / "smt-verification")
    args = ap.parse_args()

    results = verify_all()
    print("=" * 72)
    print("SMT (z3) verification of certified-inequality schemas")
    print("=" * 72)
    for r in results:
        print(f"  [{'PASS' if r.valid else 'FAIL'}] {r.name:22s} {r.description}")
    n_ok = sum(r.valid for r in results)
    all_ok = n_ok == len(results)
    print("-" * 72)
    print(f"  {n_ok}/{len(results)} schemas machine-verified by z3  (all={all_ok})")

    out = args.output_dir; out.mkdir(parents=True, exist_ok=True)
    payload = {
        "tool": "z3",
        "n_verified": n_ok, "n_total": len(results), "all_valid": all_ok,
        "schemas": [r.to_dict() for r in results],
        "claim_boundary": ("automated real-arithmetic cross-check (z3) of the "
                           "certified-inequality schemas; an independent witness for "
                           "the discharged Lean/Coq certificates, not a new physical "
                           "claim"),
    }
    (out / "smt-verification.json").write_text(json.dumps(payload, indent=2, sort_keys=True))
    lines = ["# SMT verification of certified inequalities", "",
             f"z3 independently proves **{n_ok}/{len(results)}** certified-inequality "
             "schemas valid over the reals (an automated witness alongside the "
             "discharged Lean 4 / Coq certificates).", "",
             "| Schema | Statement | z3 |", "|---|---|---|"]
    for r in results:
        lines.append(f"| {r.name} | {r.description} | {'valid' if r.valid else 'FAIL'} |")
    lines += ["", "_Generated by `scripts/verify_certificates.py`._"]
    (out / "smt-verification.md").write_text("\n".join(lines) + "\n")
    print(f"\nReport: {out / 'smt-verification.json'} (+ .md)")
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
